# Generated by Django 4.2.30 on 2026-05-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biometria_facial',
            field=models.TextField(blank=True, null=True, verbose_name='Datos del Rostro (JSON)'),
        ),
    ]
