# Generated by Django 4.2.30 on 2026-05-17 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Funko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Funko')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='funkos/', verbose_name='Imagen del Funko')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funkos', to='productos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Funko',
                'verbose_name_plural': 'Funkos',
            },
        ),
    ]
