# Generated by Django 5.2.14 on 2026-06-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_alter_categoria_nombre_delete_funko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ataque',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Ataque 1'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ataque2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Ataque 2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ataque2_dmg',
            field=models.PositiveIntegerField(default=0, verbose_name='Daño Ataque 2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ataque_desc',
            field=models.TextField(blank=True, verbose_name='Descripción del Ataque 1'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ataque_dmg',
            field=models.PositiveIntegerField(default=0, verbose_name='Daño Ataque 1'),
        ),
        migrations.AddField(
            model_name='producto',
            name='debilidad',
            field=models.CharField(default='-', max_length=50, verbose_name='Debilidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='flavor_text',
            field=models.TextField(blank=True, verbose_name='Texto de Sabor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='hp',
            field=models.PositiveIntegerField(default=0, verbose_name='HP'),
        ),
        migrations.AddField(
            model_name='producto',
            name='numero_carta',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número de Carta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='rareza',
            field=models.CharField(choices=[('comun', 'Común ★'), ('infrecuente', 'Infrecuente ★★'), ('rara', 'Rara ★★★'), ('ultra', 'Ultra Rara ★★★★')], default='comun', max_length=20, verbose_name='Rareza'),
        ),
        migrations.AddField(
            model_name='producto',
            name='retirada',
            field=models.PositiveIntegerField(default=1, verbose_name='Costo de Retirada'),
        ),
    ]
