# Generated by Django 5.2.14 on 2026-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_ataque_producto_ataque2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de Imagen (fallback)'),
        ),
    ]
